name: DeepStoragePlus
version: 1.11.6
main: me.darkolythe.deepstorageplus.DeepStoragePlus
api-version: 1.13
depend: []

commands:
  deepstorageplus:
    usage: /<command>
    aliases: [dsp]
    description: the base dsp command
    permission: deepstorageplus.command
    permission-message: You do not have permission!

permissions:
  deepstorageplus.create:
    description: Allows the user to create a DSU
    default: op
  deepstorageplus.adminopen:
    description: Allows the user to open locked DSUs
    default: op
  deepstorageplus.wireless:
    description: Allows the user to use the wireless terminal
    default: op
  deepstorageplus.give:
    description: Allows access to give command to give players items from this plugin
    default: op